### ISSUE TITLE
Cannot install via npm

### ISSUE THREAD

**Issue by lrochefort-william** [mnlsn/generator-cq-ui#1]
Got this message when I tried to install

➜  testdev  npm install -g generator-cq-ui
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "generator-cq-ui"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.0
npm ERR! code E404

npm ERR! 404 Not Found: generator-cq-ui
npm ERR! 404 
npm ERR! 404 'generator-cq-ui' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by mnlsn** [comment]
I have not added this to npm yet as I've been meaning to either deprecate it or refactor a lot of it.
